TEST CASE:  Iterator Increment Beyond End
  SideCross Iterator

StudentTest1.cpp:434: ERROR: CHECK_THROWS_AS( ++it, runtime_error ) did NOT throw at all!
